import Foundation
import Testing
@testable import VVTerm

// Test Context:
// Protects the Ghostty config text generated by VVTerm before it is loaded
// through Ghostty's C API. The invariant is that platform-specific terminal
// safety settings are explicit in the generated config while font, cursor,
// theme, and keybinding lines remain stable.
//
// These tests use pure string generation only: no Ghostty runtime, C config
// object, bundle resources, filesystem, or simulator terminal surface is
// created. Update these expectations when VVTerm intentionally changes its
// generated Ghostty config contract or adopts a new upstream iOS safety profile.
struct GhosttyConfigBuilderTests {
    #if os(macOS)
    @Test
    func macOSFontFamilyLinesUseDeterministicFallbackStack() {
        let lines = Ghostty.ConfigBuilder.fontFamilyLines(primaryFamily: "Menlo")
            .split(separator: "\n")
            .map(String.init)

        #expect(lines == [
            "font-family = \"Menlo\"",
            "font-family = \"Apple SD Gothic Neo\"",
            "font-family = \"JetBrainsMono Nerd Font\""
        ])
    }

    @Test
    func macOSFontFamilyLinesTrimWhitespaceAndDeduplicateFamilies() {
        let appleFallback = TerminalDefaults.macOSFallbackFontFamilies[0]
        let lines = Ghostty.ConfigBuilder.fontFamilyLines(primaryFamily: "  \(appleFallback)  ")
            .split(separator: "\n")
            .map(String.init)

        #expect(lines == [
            "font-family = \"Apple SD Gothic Neo\"",
            "font-family = \"JetBrainsMono Nerd Font\""
        ])
    }
    #endif

    @Test
    func fontFamilyLinesIgnoreBlankPrimaryFamily() {
        let lines = Ghostty.ConfigBuilder.fontFamilyLines(primaryFamily: "   \n  ")
            .split(separator: "\n")
            .map(String.init)

        #if os(macOS)
        #expect(lines == [
            "font-family = \"Apple SD Gothic Neo\"",
            "font-family = \"JetBrainsMono Nerd Font\""
        ])
        #else
        #expect(lines.isEmpty)
        #endif
    }

    @Test
    func fontFamilyLinesEscapeQuotesBackslashesAndNewlines() {
        let lines = Ghostty.ConfigBuilder.fontFamilyLines(primaryFamily: "A\"B\\C\nD\rE")
            .split(separator: "\n")
            .map(String.init)

        #expect(lines.first == "font-family = \"A\\\"B\\\\CDE\"")
    }

    #if os(iOS)
    @Test
    func iOSConfigContentPreservesSingleFamilyBehavior() {
        let content = Ghostty.ConfigBuilder.configContent(
            primaryFontFamily: "  JetBrainsMono Nerd Font  ",
            fontSize: 9,
            shellName: "zsh",
            themeName: "Aizen Dark"
        )

        let fontFamilyLines = content
            .split(separator: "\n")
            .map(String.init)
            .filter { $0.hasPrefix("font-family =") }

        #expect(fontFamilyLines == ["font-family = \"JetBrainsMono Nerd Font\""])
    }

    @Test
    func iOSConfigContentAppliesSafeOutputProfile() {
        // Given the iOS Ghostty config generated for a terminal surface.
        let content = Ghostty.ConfigBuilder.configContent(
            primaryFontFamily: "JetBrainsMono Nerd Font",
            fontSize: 13,
            shellName: "zsh",
            themeName: "Aizen Dark"
        )

        // When VVTerm applies its conservative iOS output profile.
        let expectedLines = [
            "image-storage-limit = 0",
            "clipboard-write = deny",
            "custom-shader = \"\"",
            "background-image = \"\"",
            "background-opacity = 1",
            "background-blur = false",
            "osc8-hyperlinks = false",
            "osc8-max-uri-bytes = 2048",
            "osc8-max-id-bytes = 256",
            "font-fallback-limit = 8",
            "glyph-atlas-max-size = 2048",
            "color-glyphs = false"
        ]

        // Then each line is present before Ghostty loads the config file.
        for expectedLine in expectedLines {
            #expect(content.contains(expectedLine))
        }
    }
    #endif

    @Test
    func configContentKeepsNonFontLinesStable() {
        let content = Ghostty.ConfigBuilder.configContent(
            primaryFontFamily: "Menlo",
            fontSize: 13,
            shellName: "fish",
            themeName: "Aizen Light"
        )

        #expect(content.contains("font-size = 13"))
        #expect(content.contains("window-inherit-font-size = false"))
        #expect(content.contains("shell-integration = fish"))
        #expect(content.contains("theme = Aizen Light"))
        #expect(content.contains("cursor-style = block"))
        #expect(content.contains("cursor-style-blink = true"))
        #expect(content.contains("keybind = shift+enter=text:\\n"))
    }

    @Test
    func configContentIncludesCursorSettings() {
        let content = Ghostty.ConfigBuilder.configContent(
            primaryFontFamily: "Menlo",
            fontSize: 13,
            shellName: "fish",
            themeName: "Aizen Light",
            cursorStyle: .bar,
            cursorBlink: false
        )

        #expect(content.contains("cursor-style = bar"))
        #expect(content.contains("cursor-style-blink = false"))
    }
}
